### ISSUE TITLE
Uncaught TypeError: Cannot read property 'repo' of null

### ISSUE THREAD

**Issue by davewmack** [igorzoriy/atom-git-status#1]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Microsoft Windows 10 Enterprise
**Thrown From**: [git-status](https://github.com/igorzoriy/atom-git-status) package, v0.2.3
### Stack Trace

Uncaught TypeError: Cannot read property 'repo' of null

```
At /D:/Users/dmack/.atom/packages/git-status/lib/GitHelper.js:10

TypeError: Cannot read property 'repo' of null
  at D:\Users\dmack\.atom\packages\git-status\lib\GitHelper.js:10:30
  at Array.forEach (native)
  at Object.getStatusList (D:\Users\dmack\.atom\packages\git-status\lib\GitHelper.js:9:31)
  at Object.toggle (D:\Users\dmack\.atom\packages\git-status\lib\GitStatus.js:51:51)
  at atom-workspace.gitStatusToggle (D:\Users\dmack\.atom\packages\git-status\lib\GitStatus.js:36:22)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (D:\Users\dmack\AppData\Local\atom\app-1.0.19\resources\app.asar\src\command-registry.js:245:29)
  at D:\Users\dmack\AppData\Local\atom\app-1.0.19\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (D:\Users\dmack\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (D:\Users\dmack\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (D:\Users\dmack\AppData\Local\atom\app-1.0.19\resources\app.asar\src\window-event-handler.js:184:20)

```
### Commands

```
     -5:23.5.0 snippets:expand (atom-text-editor.editor.is-focused)
     -5:23.5.0 editor:indent (atom-text-editor.editor.is-focused)
  5x -5:22.7.0 git-status:toggle (atom-text-editor.editor.is-focused)
  2x -4:53.1.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -4:51.8.0 git-status:toggle (atom-text-editor.editor.is-focused)
     -4:43.7.0 core:select-all (atom-text-editor.editor.is-focused)
  6x -4:42.7.0 git-status:toggle (atom-text-editor.editor.is-focused)
     -3:55.3.0 core:paste (atom-text-editor.editor.is-focused)
 11x -3:54 git-status:toggle (atom-text-editor.editor.is-focused)
     -2:21.6.0 core:cut (atom-text-editor.editor.is-focused)
  5x -2:21.3.0 git-status:toggle (atom-text-editor.editor.is-focused)
     -1:55.7.0 core:save-as (atom-text-editor.editor)
     -0:39.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:38.7.0 git-status:toggle (atom-text-editor.editor.is-focused)
     -0:21.1.0 application:add-project-folder (ul.list-inline.tab-bar.inset-panel)
     -0:03.4.0 git-status:toggle (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai-seti"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.28.14
auto-detect-indentation, v0.4.2
git-status, v0.2.3
highlight-selected, v0.10.1
json-schema, v0.1.15
language-rust, v0.4.5
minimap-highlight-selected, v4.3.1
monokai-seti, v0.7.0
open-recent, v2.3.0
pigments, v0.17.1
react-snippets, v0.2.0
semantic-ui, v1.0.7

# Dev
No dev packages
```

**Comment by igorzoriy** [comment]
@davewmack Thanks for response. Try to use new version.
